### ISSUE TITLE
Is it possible to set graphql_name to snake_case instead of camelCase?

### ISSUE THREAD

**Issue by gu3sss** [profusion/sgqlc#107]
Is it possible to set graphql_name to snake_case instead of camelCase?

This is how my schema looks currently,

> ```class PipelineAccessNode(sgqlc.types.Type, Node):
>     __schema__ = sgqlc_schema
>     __field_names__ = ('pipeline_id', 'user_type', 'user_info')
>     pipeline_id = sgqlc.types.Field(sgqlc.types.non_null(String), graphql_name='pipelineId')
>     user_type = sgqlc.types.Field(sgqlc.types.non_null(String), graphql_name='userType')
>     user_info = sgqlc.types.Field(sgqlc.types.non_null(String), graphql_name='userInfo')

I expect it to be,

> ```class PipelineAccessNode(sgqlc.types.Type, Node):
>     __schema__ = sgqlc_schema
>     __field_names__ = ('pipeline_id', 'user_type', 'user_info')
>     pipeline_id = sgqlc.types.Field(sgqlc.types.non_null(String), graphql_name='pipeline_id')
>     user_type = sgqlc.types.Field(sgqlc.types.non_null(String), graphql_name='user_type')
>     user_info = sgqlc.types.Field(sgqlc.types.non_null(String), graphql_name='user_info')

**Comment by barbieri** [comment]
what you mean? The `sgqlc-codegen`  should read the `graphql_name` from your GraphQL schema file and use those names. Let me know if that's not happening.

However, if you're manually writing them, you can use whatever name you want.

**Comment by gu3sss** [comment]
My GraphQl schema file doesn't have any names hard coded. All my db models are defined in SqlAlchemy and am using Graphene (https://docs.graphene-python.org/projects/sqlalchemy/en/latest/) to import the models to my schema. The field names in my db models are in snake_case. I guess I am running into the behavior mentioned here https://readthedocs.org/projects/sgqlc/.

<img width="846" alt="image" src="https://user-images.githubusercontent.com/24322470/86837579-1ab10b00-c06d-11ea-96c7-e45853a08eb9.png">

**Comment by barbieri** [comment]
ok, but how are you generating the file you pasted in the original question? If you're using some schema (.json or .graphql or .gql), could you send me or paste one snippet (like the one declaring `pipeline_id`)

**Comment by barbieri** [comment]
as for the highlighted description, that part is when you **do not** declare the `graphql_name='explicit_value_here'`.

**Comment by gu3sss** [comment]
Here's a snip from my models.py,

> ```class PipelineAccess(Base):
>     __tablename__ = 't_pipeline_access'
>     id = Column(Integer(), primary_key=True)
>     pipeline_id = Column(String(40), nullable=False)
>     user_type = Column(String(50), nullable=False)
>     user_info = Column(String(50), nullable=False)

Here's my graphql_schema.py file,

> ```import graphene
> 
> from graphene import Connection, Node
> from graphene_sqlalchemy import SQLAlchemyObjectType
> from graphql_operations.graphql_filter import MyFilterableConnectionField
> 
> from db_models.models import PipelineAccess
> from utils.misc import DbSession
> 
> 
> class PipelineAccessNode(SQLAlchemyObjectType):
>     class Meta:
>         model = PipelineAccess
>         interfaces = (Node,)
>         connection_field_factory = MyFilterableConnectionField.factory
> 
> 
> class PipelineAccessConnection(Connection):
>     class Meta:
>         node = PipelineAccessNode
> 
> 
> class Query(graphene.ObjectType):
>     access = graphene.relay.Node.Field(PipelineAccessNode)
>     all_access = MyFilterableConnectionField(PipelineAccessConnection)
> 
> 
> schema = graphene.Schema(
>     query=Query,
>     types=[
>         PipelineAccessNode
>     ]
> )
> 
> 
> def gql_execute(gql_query):
>     with DbSession() as db_session:
>         exec_result = schema.execute(str(gql_query),
>                                      context_value={'session': db_session})
>         resp_body = {
>           "data": dict(exec_result.data)
>           if exec_result.data is not None else None,
>         }
>         if exec_result.errors is not None:
>             resp_body['errors'] = []
>             for error in exec_result.errors:
>                 resp_body['errors'].append(str(error))
>         return resp_body
> 

Here's my graphql_filter.py,

> ```from graphene_sqlalchemy_filter import FilterableConnectionField, FilterSet
> from db_models.models import PipelineAccess
> 
> 
> class PipelineAccessFilter(FilterSet):
>     class Meta:
>         model = PipelineAccess
>         fields = {
>             'pipeline_id': ['eq', 'ne', 'in', 'ilike'],
>             'user_info': ['eq', 'ne', 'in', 'ilike'],
>             'user_type': ['eq', 'ne', 'in', 'ilike']
>         }
> 
> 
> class MyFilterableConnectionField(FilterableConnectionField):
>     filters = {
>         PipelineAccess: PipelineAccessFilter()
>     }
> 


Here's my graphql_Ssgqlc_schema.py generated by SGQLC codegen,

> ```import sgqlc.types
> import sgqlc.types.datetime
> import sgqlc.types.relay
> 
> sgqlc_schema = sgqlc.types.Schema()
> 
> # Unexport Node/PageInfo, let schema re-declare them
> sgqlc_schema -= sgqlc.types.relay.Node
> sgqlc_schema -= sgqlc.types.relay.PageInfo
> 
> ########################################################################
> # Scalars and Enumerations
> ########################################################################
> Boolean = sgqlc.types.Boolean
> 
> DateTime = sgqlc.types.datetime.DateTime
> 
> ID = sgqlc.types.ID
> 
> Int = sgqlc.types.Int
> 
> 
> class PipelineAccessNodeSortEnum(sgqlc.types.Enum):
>     __schema__ = sgqlc_schema
>     __choices__ = ('ID_ASC', 'ID_DESC', 'PIPELINE_ID_ASC', 'PIPELINE_ID_DESC',
>                    'USER_TYPE_ASC', 'USER_TYPE_DESC', 'USER_INFO_ASC',
>                    'USER_INFO_DESC')
> 
> 
> String = sgqlc.types.String
> 
> 
> ########################################################################
> # Input Objects
> ########################################################################
> 
> 
> class PipelineAccessFilter(sgqlc.types.Input):
>     __schema__ = sgqlc_schema
>     __field_names__ = (
>         'pipeline_id', 'pipeline_id_ne', 'pipeline_id_in', 'pipeline_id_ilike',
>         'user_type', 'user_type_ne', 'user_type_in', 'user_type_ilike',
>         'user_info', 'user_info_ne', 'user_info_in', 'user_info_ilike',
>         'and_', 'or_', 'not_')
> 
>     pipeline_id = sgqlc.types.Field(String, graphql_name='pipelineId')
>     pipeline_id_ne = sgqlc.types.Field(String, graphql_name='pipelineIdNe')
>     pipeline_id_in = sgqlc.types.Field(
>         sgqlc.types.list_of(sgqlc.types.non_null(String)),
>         graphql_name='pipelineIdIn')
>     pipeline_id_ilike = sgqlc.types.Field(String,
>                                           graphql_name='pipelineIdIlike')
>     user_type = sgqlc.types.Field(String, graphql_name='userType')
>     user_type_ne = sgqlc.types.Field(String, graphql_name='userTypeNe')
>     user_type_in = sgqlc.types.Field(
>         sgqlc.types.list_of(sgqlc.types.non_null(String)),
>         graphql_name='userTypeIn')
>     user_type_ilike = sgqlc.types.Field(String, graphql_name='userTypeIlike')
>     user_info = sgqlc.types.Field(String, graphql_name='userInfo')
>     user_info_ne = sgqlc.types.Field(String, graphql_name='userInfoNe')
>     user_info_in = sgqlc.types.Field(
>         sgqlc.types.list_of(sgqlc.types.non_null(String)),
>         graphql_name='userInfoIn')
>     user_info_ilike = sgqlc.types.Field(String, graphql_name='userInfoIlike')
>     and_ = sgqlc.types.Field(
>         sgqlc.types.list_of(sgqlc.types.non_null('PipelineAccessFilter')),
>         graphql_name='and')
>     or_ = sgqlc.types.Field(
>         sgqlc.types.list_of(sgqlc.types.non_null('PipelineAccessFilter')),
>         graphql_name='or')
>     not_ = sgqlc.types.Field('PipelineAccessFilter', graphql_name='not')
> 
> 
> ########################################################################
> # Output Objects and Interfaces
> ########################################################################
> 
> 
> class Node(sgqlc.types.Interface):
>     __schema__ = sgqlc_schema
>     __field_names__ = ('id',)
>     id = sgqlc.types.Field(sgqlc.types.non_null(ID), graphql_name='id')
> 
> 
> class PageInfo(sgqlc.types.Type):
>     __schema__ = sgqlc_schema
>     __field_names__ = (
>         'has_next_page', 'has_previous_page', 'start_cursor', 'end_cursor')
>     has_next_page = sgqlc.types.Field(sgqlc.types.non_null(Boolean),
>                                       graphql_name='hasNextPage')
>     has_previous_page = sgqlc.types.Field(sgqlc.types.non_null(Boolean),
>                                           graphql_name='hasPreviousPage')
>     start_cursor = sgqlc.types.Field(String, graphql_name='startCursor')
>     end_cursor = sgqlc.types.Field(String, graphql_name='endCursor')
> 
> 
> class PipelineAccessConnection(sgqlc.types.relay.Connection):
>     __schema__ = sgqlc_schema
>     __field_names__ = ('page_info', 'edges')
>     page_info = sgqlc.types.Field(sgqlc.types.non_null(PageInfo),
>                                   graphql_name='pageInfo')
>     edges = sgqlc.types.Field(
>         sgqlc.types.non_null(sgqlc.types.list_of('PipelineAccessEdge')),
>         graphql_name='edges')
> 
> 
> class PipelineAccessEdge(sgqlc.types.Type):
>     __schema__ = sgqlc_schema
>     __field_names__ = ('node', 'cursor')
>     node = sgqlc.types.Field('PipelineAccessNode', graphql_name='node')
>     cursor = sgqlc.types.Field(sgqlc.types.non_null(String),
>                                graphql_name='cursor')
> 
> 
> class Query(sgqlc.types.Type):
>     __schema__ = sgqlc_schema
>     __field_names__ = ('access', 'all_access')
>     access = sgqlc.types.Field('PipelineAccessNode', graphql_name='access',
>                                args=sgqlc.types.ArgDict((
>                                      ('id',
>                                       sgqlc.types.Arg(sgqlc.types.non_null(ID),
>                                                       graphql_name='id',
>                                                       default=None)),
>                                ))
>                                )
>     all_access = sgqlc.types.Field(PipelineAccessConnection,
>                                    graphql_name='allAccess',
>                                    args=sgqlc.types.ArgDict((
>                                        ('filters',
>                                         sgqlc.types.Arg(PipelineAccessFilter,
>                                                         graphql_name='filters',
>                                                         default=None)),
>                                        ('sort', sgqlc.types.Arg(
>                                            sgqlc.types.list_of(
>                                                PipelineAccessNodeSortEnum),
>                                            graphql_name='sort',
>                                            default=['ID_ASC'])),
>                                        ('before', sgqlc.types.Arg(
>                                            String, graphql_name='before',
>                                            default=None)),
>                                        ('after', sgqlc.types.Arg(
>                                            String, graphql_name='after',
>                                            default=None)),
>                                        ('first', sgqlc.types.Arg(
>                                            Int, graphql_name='first',
>                                            default=None)),
>                                        ('last', sgqlc.types.Arg(
>                                            Int, graphql_name='last',
>                                            default=None)),
>                                    ))
>                                    )
> 
> 
> class PipelineAccessNode(sgqlc.types.Type, Node):
>     __schema__ = sgqlc_schema
>     __field_names__ = ('pipeline_id', 'user_type', 'user_info')
>     pipeline_id = sgqlc.types.Field(sgqlc.types.non_null(String),
>                                     graphql_name='pipelineId')
>     user_type = sgqlc.types.Field(sgqlc.types.non_null(String),
>                                   graphql_name='userType')
>     user_info = sgqlc.types.Field(sgqlc.types.non_null(String),
>                                   graphql_name='userInfo')
> 
> 
> ########################################################################
> # Unions
> ########################################################################
> 
> ########################################################################
> # Schema Entry Points
> ########################################################################
> sgqlc_schema.query_type = Query
> sgqlc_schema.mutation_type = None
> sgqlc_schema.subscription_type = None

**Comment by gu3sss** [comment]
I guess the culprit might be Graphene library too. Guess graphene might convert snake_case to camelCase in the schema. I am investigating further on the same.

**Comment by gu3sss** [comment]
Confirmed! Its Graphene. Sorry about the false alarm! Closing the issue. Thanks for checking on it anyways.
