### ISSUE TITLE
sessions support for requests

### ISSUE THREAD

**Issue by vavalomi** [profusion/sgqlc#108]
Can you publish the latest changes to the pypi please? for local development I can use direct github link to the latest commit as dependency I'd like to refer to it from my published package (setup.py doesn't seem to support direct links)

**Comment by barbieri** [comment]
https://github.com/profusion/sgqlc/releases/tag/v11.0
https://pypi.org/project/sgqlc/11.0/

**Comment by vavalomi** [comment]
perfect!
