### ISSUE TITLE
Include graphql_to_python in SGQLC library

### ISSUE THREAD

**Issue by n-wach** [profusion/sgqlc#109]
I'm working to create an Python library for a GraphQL API, built on top of auto-generated SGQLC using bin/codegen.  One feature we have is to automatically remove problematic fields from queries (so if you request all fields on an object, but the server returns an error for one, the request will be repeated excluding that field).  Unfortunately, the server errors return fields using GraphQL names, whereas we need to exclude using python names.

We would like to reuse the graphql to python conversion used by codegen, but it unfortunately isn't present anywhere in the library.  Would it be possible to include `graphql_to_python` (along with the regex) within SGQLC?

https://github.com/profusion/sgqlc/blob/22dfb5117cb5dec92162314f0fd24aedd31c7cd6/bin/sgqlc-codegen#L252

Currently we reimplement it ourselves, but ideally would use the same function.  I think it would be great to move it next to `_to_graphql_name`

https://github.com/profusion/sgqlc/blob/cec911b73a0922a55ff59f57db40e5b78d112143/sgqlc/types/__init__.py#L2020

Happy to create a PR.

**Comment by barbieri** [comment]
sorry taking so long, I'm fine to move this or create an `utils.py` file, both work.

If during your work you find `sglc-codegen` is something that should be made a lib, we can convert it and only keep the argparse and the likes in the `bin/sgql-codegen`.

do you have some time to work on this?

**Comment by n-wach** [comment]
I'll create a PR moving it to `BaseItem` for now. Don't currently need anything else in `codegen`, might be good to eventually make it a lib tho.

**Comment by n-wach** [comment]
Created #111 

@barbieri
