### ISSUE TITLE
Add extension to sgqlc-codegen so it works on windows

### ISSUE THREAD

**Issue by Mause** [profusion/sgqlc#113]

**Comment by barbieri** [comment]
could you share more info on what's not working?

I don't have any windows machine to run, but given a system with Python installed, it should work.

**Comment by Mause** [comment]
If a file doesn't have a file extension on windows, it doesn't know what do to with it - the usual solution is either to add `.py` to the filename, or include another script (usually `.cmd` or `.bat`) that runs the python file

**Comment by barbieri** [comment]
do you have an example of how other sw do? I thought setuptools https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html would handle it for me

**Comment by Mause** [comment]
Look at the second heading on that page: https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html#the-console-scripts-entry-point

**Comment by barbieri** [comment]
@Mause let me know if it worked, otherwise reopen the ticket

**Comment by Mause** [comment]
@barbieri that works perfectly, thankyou 😊
