### ISSUE TITLE
Automatic creation of classes based of GraphQL schema

### ISSUE THREAD

**Issue by gioxc88** [profusion/sgqlc#118]
Hello and thank you for this amazing package.

I wanted to ask how if you have an approximate ETA for this feature since you mention it in the documentation.
It would be super useful.

Thank you
Gio

**Comment by barbieri** [comment]
not sure what you mean, the classes are created by `sgqlc-codegen` for a while, more recently I even added the option to create the operations from GraphQL DSL.

**Comment by gioxc88** [comment]
Sorry to have opened the issue. I didn't go through all documentation because at some point you say 

"Future plans include generating the Python classes from the GraphQL schema, which can be automatically fetched from an endpoint using the introspection query."

This is what confused me. I successfully used `sgqlc-codegen`.
Thank you, this can be closed

**Comment by barbieri** [comment]
ok, thanks. Fixed that in the readme
