### ISSUE TITLE
Mutation input

### ISSUE THREAD

**Issue by jcmlima-t4s** [profusion/sgqlc#120]
First: any Forum where users can exchange experiences and doubts?

Love this project, I've been using to Query api's of all type and complex.
More a question than an issue.

For mutations I couldn't find complex examples.

I need to construct a mutation like 

`mutation {
  createCard(
            input:{
                pipe_id: 301422830,
                title: "via api"
            }
  ) {
		clientMutationId
  }
}`

but only manage to create something as 

`mutation {
  createCard(pipeId: 100, title: "test") {
    ClientMutationId
  }
}`

couldn't find a way to have the 2 levels of input to the mutation.

My code
[example](https://gist.github.com/jcmlima-t4s/789079c89f2827f3f32db8752cba9312)

**Comment by barbieri** [comment]
Hi @jcmlima-t4s, we didn't, all was being done here as issues. I see that GitHub added Discussions support to projects, so I enabled it [SGQLC Discussions](https://github.com/profusion/sgqlc/discussions)

As for your question, take a look at:
 - [Input](https://sgqlc.readthedocs.io/en/latest/sgqlc.types.html#sgqlc.types.Input.__init__)
 - [Operation](https://sgqlc.readthedocs.io/en/latest/sgqlc.operation.html#sgqlc.operation.Operation) there is an example I replicate below

```py
from datetime import datetime, timezone
from sgqlc.types import global_schema
op = Operation()
repository = op.repository(id='sgqlc')
issues = repository.issues(filter=global_schema.IssuesFilter(
    reporter=[global_schema.ReporterFilterInput(name_contains='Gustavo')],
    start_date=datetime(2019, 1, 1, tzinfo=timezone.utc),
))
```

In this case, `IssuesFilter` and `ReporterFilterInput` are complex types (`Input`).

**Comment by mazohssister** [comment]
Hey, I had almost the same issue and solve it through the pain and tears. Hope somebody find it helpful :)

My query need to be like this (it contains data as a list on the 2nd level):

`mutation {
  addRequests(data: [
    {
      service: FraudlentResource, value: "gtw-02.eexample.com" 
    }
  ]`



```
from sgqlc.operation import Operation

op = Operation(Mutations)
dic = {'service': 'FraudlentResource', 'value': 'https://wower.com'}
data = [dic]
op.add_requests(data=data)
```

**Comment by barbieri** [comment]
since not an issue, closing this, ok?
