### ISSUE TITLE
sgqlc-codegen operation validates arguments against python name

### ISSUE THREAD

**Issue by XuluWarrior** [profusion/sgqlc#124]
With a query like this
```
query allQuotes($startTimestamp: DateTime!) {
  allQuotes(startTimestamp: $startTimestamp) {
    ...
  }
}
```
`sgqlc-codegen operation` fails to validate the argument.  This is because it inconsistently uses the python name (`start_timestamp`) and the GraphQL name (`startTimestamp`)

I have created a PR which fixes the issue as I see it. #123

**Comment by barbieri** [comment]
thank you very much! :-)

**Comment by XuluWarrior** [comment]
Thanks for reviewing it so quickly :)
