### ISSUE TITLE
Name-wrangling fields with invalid Python names

### ISSUE THREAD

**Issue by AndreasVoellmy** [profusion/sgqlc#13]
A GQL schema might have types with fields that aren't valid Python names. For example, you might have 
```
type IntRange {
  from: Int
  to: Int
}
```
`from` is a Python keyword, so the code generated by `sgqlc-codegen` cannot be loaded. It would be nice if `sgqlc-codegen` could mangle these names to make them legal. As a straw man, maybe it could append an underscore (e.g. `from_`) to make it valid.

**Comment by barbieri** [comment]
@AndreasVoellmy could you check if the branch `codegen-python-keywords` fixes your issue? if so I'll merge to master

**Comment by barbieri** [comment]
Hi @AndreasVoellmy, could you check this fixes your issue?

**Comment by barbieri** [comment]
timed out... merged in master, please let me know if it more fixes are required.
