### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by KlausSchaefers** [profusion/sgqlc#131]
It is not clear how the variable substitution works. Could you add some section in the documentation?

**Comment by barbieri** [comment]
will do, you mean how to declare you want to use one, or how to pass them?

Until I have time to get to it, please see if this helps:

https://sgqlc.readthedocs.io/en/latest/sgqlc.operation.html
> Operations can also have argument (variables), in this case it must be named (otherwise a name is created based on root type name, such as "Query"):

```py
>>> from sgqlc.types import Variable
>>> op = Operation(repo_id=str, reporter_login=str)
>>> repository = op.repository(id=Variable('repo_id'))
>>> issues = repository.issues(reporter_login=Variable('reporter_login'))
>>> issues.__fields__('number', 'title')
>>> op # or repr(), prints out GraphQL!
query Query($repoId: String, $reporterLogin: String) {
  repository(id: $repoId) {
    issues(reporterLogin: $reporterLogin) {
      number
      title
    }
  }
}
```

> If variable name conflicts with the parameter, you can pass them as a single variables parameter containing a dict.
```py
>>> op = Operation(name='MyOperation', variables={'name': str})
>>> op.repository(id=Variable('name')).name()
name
>>> op # or repr(), prints out GraphQL!
query MyOperation($name: String) {
  repository(id: $name) {
    name
  }
}
```

**Comment by barbieri** [comment]
In other to send requests with variables, see https://sgqlc.readthedocs.io/en/latest/sgqlc.endpoint.base.html#sgqlc.endpoint.base.BaseEndpoint.__call__ you send them after the query

**Comment by barbieri** [comment]
[BaseEndpoint.__call__](https://sgqlc.readthedocs.io/en/latest/sgqlc.endpoint.base.html#sgqlc.endpoint.base.BaseEndpoint.__call__) now covers it in more depth, with an example on the beginning of that page and some other text in the [Operation - Performance](https://sgqlc.readthedocs.io/en/latest/sgqlc.operation.html#performance)

closing this, there is always room for improvements and PRs are welcome :-)
