### ISSUE TITLE
Code generation for Interfaces not working correctly

### ISSUE THREAD

**Issue by maaft** [profusion/sgqlc#132]
Hi,

first of all - thank you very much for this great piece of work.
I have some problems with code generation. Attached you find my schema.json and my operations.gql so you can reproduce this.

First, types that implement interfaces are not correctly used in the generated operations.py:
![image](https://user-images.githubusercontent.com/2518993/111682627-e52c0680-8824-11eb-98f9-63d1f704fb82.png)

Steps to reproduce:
1. `sgqlc-codegen schema schema.json schema.py`
2. `sgqlc-codegen operation --schema schema.json client:schema operations.py operations.gql`
3. Open operations.py and note that `BarBaz` cannot be found. Either an import is missing or the codegen should put out `client.BarBaz` instead.

Second, is it possible to get auto-completion in vscode for the generated operations? Currently the derived type seems to be `Any`. I'm currently using pylance but can of course use something else.

![image](https://user-images.githubusercontent.com/2518993/111682762-055bc580-8825-11eb-93cd-cee0ebdfd693.png)

[client.zip](https://github.com/profusion/sgqlc/files/6166602/client.zip)

**Comment by barbieri** [comment]
I'll take a look at the bug, that `BarBaz` should be used inside `client.schema`, so definitely missing it. But it will take me some time, currently busy with some work projects.

As for your second point, unfortunately that's bit harder due the usage of meta classes. What I plan to do someday is to generate that for queries, see #129

**Comment by maaft** [comment]
I can surely write a PR. Can you point me into the right direction maybe where the code might fail?

**Comment by maaft** [comment]
Can you please approve https://github.com/profusion/sgqlc/pull/134 ?
