### ISSUE TITLE
When variable-name differs from graphqlName, an error is thrown.

### ISSUE THREAD

**Issue by maaft** [profusion/sgqlc#133]
See https://github.com/profusion/sgqlc/commit/9c7444962b06af432937b6655087e152e37f0f8e

**Comment by barbieri** [comment]
could you test #145?

**Comment by dupuy26** [comment]
I had this same problem with the 12.2 release when I upgraded to get the fix for issue #119, but the current 13.0.dev20210508 release doesn't have this problem, so #145 seems like a good fix.

**Comment by barbieri** [comment]
thanks! :-)
