### ISSUE TITLE
Question: How to convert JSONString to JSON when using SGQLC

### ISSUE THREAD

**Issue by gu3sss** [profusion/sgqlc#148]
Couple of columns in my mysql backend table are of type JSON. When trying to use SGQLC codegen to generate the schema, I see that Sgqlc marked these field with type 'JSONString'. This JSONString displays as String in response obviously and I am expecting the response to be in JSON format. Is this acheivable?

Please refer to the `status_types_for_notification` and `email_ids` fields below.

Expected result:

```{
  "message": {
    "data": {
      "all_status": {
        "pageInfo": {
          "startCursor": "YXJyYXljb25uZWN0aW9uOjA=",
          "endCursor": "YXJyYXljb25uZWN0aW9uOjE=",
          "hasNextPage": false
        },
        "total_count": 2,
        "edges": [
          {
            "cursor": "YXJyYXljb25uZWN0aW9uOjA=",
            "node": {
              "id": "Q29tcG9uZW50U3RhdHVzTm9kZTooJ2M5YjM5MTc3LWExYjUtNDgwYy04NGRhLTZmOWNiZDNhM2QyZScsICdPSScsIDAp",
              "pipeline_id": "c9b39177-a1b5-480c-84da-6f9cbd3a3d2e",
              "status_types_for_notification": [
                "SUCCEEDED",
                "FAILED"
              ],
              "email_ids": [
                "email1",
                "email2"
              ]
            }
          }
        ]
      }
    }
  }
}
```
Actual Result:

```{
    "message": {
        "data": {
            "all_status": {
                "pageInfo": {
                    "startCursor": "YXJyYXljb25uZWN0aW9uOjA=",
                    "endCursor": "YXJyYXljb25uZWN0aW9uOjE=",
                    "hasNextPage": false
                },
                "total_count": 2,
                "edges": [
                    {
                        "cursor": "YXJyYXljb25uZWN0aW9uOjA=",
                        "node": {
                            "id": "Q29tcG9uZW50U3RhdHVzTm9kZTooJ2M5YjM5MTc3LWExYjUtNDgwYy04NGRhLTZmOWNiZDNhM2QyZScsICdPSScsIDAp",
                            "pipeline_id": "c9b39177-a1b5-480c-84da-6f9cbd3a3d2e",
                            "status_types_for_notification": "[\"SUCCEEDED\", \"FAILED\"]",
                            "email_ids": "[\"email1\", \"email2\"]"
                        }
                    }
                ]
            }
        }
    }
}

**Comment by barbieri** [comment]
yes, you need to declare them as scalars, refer to the built-in such as https://github.com/profusion/sgqlc/blob/master/sgqlc/types/datetime.py 

do you write this schema manually? If so, just declare a type like that and refer to it. If you don't, if you use schemagen, I'm afraid I don't have any code that will import some extra file and use it (like it does for Relay/Node and DateTime), but it's easy to add and I can do it for you

**Comment by barbieri** [comment]
@gu3sss ping? do you have more details?

**Comment by gu3sss** [comment]
Am sorry for the delay! I am not using schemagen. I created my own schema mentioned [here](https://github.com/profusion/sgqlc/issues/107#issuecomment-655235400).

**Comment by gu3sss** [comment]
Are you suggesting me to build a new scalar of type Json just for my code or to contribute back to SGQLC community?

**Comment by barbieri** [comment]
that can be the case as well, but if you don't want to contribute back you can simply use it in your schema, you declare a class  (like those in `sgqlc/types/datetime.py`) and then you use it in the schema declaration.

**Comment by gu3sss** [comment]
understood! I will give it a shot. thanks!

**Comment by barbieri** [comment]
@gu3sss any updates on this?

**Comment by gu3sss** [comment]
@barbieri Please close this. I implemented a work around for this.

**Comment by gu3sss** [comment]
I post processed the output I got using graphql.
