### ISSUE TITLE
Variable representing list_of

### ISSUE THREAD

**Issue by catalyst17** [profusion/sgqlc#149]
Hello!

I've looked for the similar issues, might be related to [this](https://github.com/profusion/sgqlc/issues/125#issuecomment-770388009). However, though I am using the latest version I still have `'Variable' object is not iterable` error being raised.

My generated query looks like this:
```python
def query_top_pairs():
    _op = sgqlc.operation.Operation(_schema_root.query_type, name='TopPairs', variables=dict(limit=sgqlc.types.Arg(sgqlc.types.non_null(_schema.Int)), excludeTokenIds=sgqlc.types.Arg(sgqlc.types.non_null(sgqlc.types.list_of(sgqlc.types.non_null(_schema.String))))))
    _op_pairs = _op.pairs(first=sgqlc.types.Variable('limit'), order_by='reserveUSD', order_direction='desc', where={'token0_not_in': sgqlc.types.Variable('excludeTokenIds'), 'token1_not_in': sgqlc.types.Variable('excludeTokenIds')})
```

So, `$excludeTokenIds` variable should actually be the iterable `list_of(str)`.
I have tracked down the exception cause to this [line](https://github.com/profusion/sgqlc/blob/5360cae08375136202e4ef5176148d2ca2e45aca/sgqlc/types/__init__.py#L973). It actually tries to iterate through the `json_data` while it is represented by a `sgqlc.types.Variable type`, which seems to have only string names. 
```python
def _create_list_of_wrapper(name, t):
    'creates type wrapper for list of given type'
    def realize_type(v, selection_list=None):
        if isinstance(v, (t, Variable)):  # pragma: no cover
            return v
        return t(v, selection_list)

    def __new__(cls, json_data, selection_list=None):
        if json_data is None:
            return None

        return [realize_type(v, selection_list) for v in json_data]
```
I am pretty sure I do not get the whole concept of how this code works, but something could be wrong here. Will appreciate any help, thanks in advance!

**Comment by barbieri** [comment]
I'll take a look.

Do you have a trace back or can put together a public repo where I can run to get the error (or maybe just use the GitHub/Shopify examples, change them to produce this error).

**Comment by barbieri** [comment]
btw, I'm 99% sure the  `if isinstance(v, (t, Variable))` is something that should be in the `__new__`, like:

```py
    def __new__(cls, json_data, selection_list=None):
        if json_data is None:
            return None

       if isinstance(json_data, (t, Variable)):
            return json_data
 
        return [realize_type(v, selection_list) for v in json_data]
```

**Comment by catalyst17** [comment]
Yooo, works like magic with this! Will you fix it or should I make a PR?

**Comment by barbieri** [comment]
done :-)
