### ISSUE TITLE
sgqlc-codegen with wrong shebang

### ISSUE THREAD

**Issue by guludo** [profusion/sgqlc#15]
When I tried running the code generator, I got the following error: 
```
bash: /usr/bin/sgqlc-codegen: /Users/gustavo/.local/share/virtualenvs/sgqlc-LJ804sPL/bin/python3: bad interpreter: No such file or directory
```

Then I looked into the python script and, indeed, the script's shebang is using that path for the interpreter.

**Comment by barbieri** [comment]
https://stackoverflow.com/questions/33792696/how-to-prevent-python-wheel-from-expanding-shebang

**Comment by guludo** [comment]
> damn it... will check, looks like something took my virtualenv and changed the shebang. Is that pip? or git?

pip

**Comment by guludo** [comment]
Thanks. I can use `python /usr/bin/sgqlc-codegen` in the meantime.

**Comment by barbieri** [comment]
see new release if it fixes

**Comment by guludo** [comment]
Fixed, thanks!

**Comment by lubo** [comment]
Looks like v4.0 is affected too.

**Comment by barbieri** [comment]
damn, indeed a bug. I released from within the pipenv, creating the buggy shebang. Will do a v5 with the new features and correct interpreter.
