### ISSUE TITLE
sgqlc prevents usage of python 'requests' library 

### ISSUE THREAD

**Issue by catalyst17** [profusion/sgqlc#154]
Feeling already sorry for dumping this really useful project with issues for the third day in a row, but I've confronted another problem while trying to use sgqlc along with python `requests` library.
The module `sgqlc.endpoint.requests` seems to be used instead. It's a common problem and people suggest renaming one of the modules, cause bare [aliases won't help](https://stackoverflow.com/a/5063268).
Have not found any discussions about that here, therefore am opening a new issue, probably some other solution can be suggested or the module renamed. Thanks!

UPD. Tried to use `urllib3` instead, also not possible, so the problem might be bigger than just module name collision:
![image](https://user-images.githubusercontent.com/37663786/120492326-a5f06900-c3c2-11eb-8df6-7eb2a5aa9dc8.png)

**Comment by barbieri** [comment]
no problem to send issues, but I need more context. This screenshot doesn't tell me much :-)

As for requests module, I'm not an user, but the guys that contributed it said it worked well, they were using requests elsewhere.

Where are you placing this file? What are you importing?

**Comment by catalyst17** [comment]
Sorry for the long wait, I was able to fix the problem by uninstalling `urllib3` and installing it back. Cannot say for sure now, if it's a problem of your library or my own setup, but somehow a few libraries that are being used by `sgqlc` had empty `__init__.py` files before reinstallation. So the thing is actually narrowing to disability of using these libraries without manual reinstallation. I will try to reproduce it with _shopify_ example now.

**Comment by catalyst17** [comment]
Seems to be my own setup problem. Closing the issue :)

**Comment by catalyst17** [comment]
Seems to be my own setup problem. Closing the issue :)
