### ISSUE TITLE
Object creation using aliases

### ISSUE THREAD

**Issue by lukavia** [profusion/sgqlc#16]
Thank you very much for your great work. 
In my use case I need to use aliases since I have to get to sets of nodes filter by different parameters. 
Using your example I use: 
```pytnon
issues = op.repository(owner=owner, name=name).issues(__alias__='issues_alias', first=100)
```
But then later on when I use
```python
repo = (op + data).repository
print(repo)
```
I don't get the desired Class...
May by I'm missing something, but can you suggest or make an example of the wright approach for using \_\_alias__ ?
Thank you

**Comment by barbieri** [comment]
Hi, I don’t recall out of my head, as soon as I get to a dev machine I’ll let you know.

Meanwhile, if you can provide a Python session with the print results and errors, I may remember

**Comment by lukavia** [comment]
There is no error. 
The query is generated correctly:
```python
... print(op)
query {
  repository(owner: "profusion", name: "sgqlc") {
    issues_alias: issues(first: 100) {
      nodes {
        number
        title
      }
      pageInfo {
        hasNextPage
        endCursor
      }
    }
  }
}
```
And it is executed correctly with data returned:
```python
>> data = endpoint(op)
>>> print(data)
{'data': {'repository': {'issues_alias': {'nodes': [{'number': 1, 'title': 'unit tests: sgqlc.types'}, {'number': 2, 'title': 'unit tests: sgqlc.operation'}, {'number': 3, 'title': 'add GraphQL inline fragment support'}, {'number': 4, 'title': 'add GraphQL named fragment support'}, {'number': 5, 'title': 'Auto interpret Union in results'}, {'number': 6, 'title': 'Support @directive(arg: value)'}, {'number': 7, 'title': 'Auto generate schema from Introspection'}, {'number': 8, 'title': 'aiohttp endpoint'}, {'number': 12, 'title': 'HTTPEndpoint timeout invalid'}, {'number': 13, 'title': 'Name-wrangling fields with invalid Python names'}, {'number': 15, 'title': 'sgqlc-codegen with wrong shebang'}, {'number': 16, 'title': 'Object creation using aliases'}], 'pageInfo': {'hasNextPage': False, 'endCursor': 'Y3Vyc29yOnYyOpHOF8CY4A=='}}}}}
```
The only problem is that it doesn't transform to objects:
```python
>>> repo = (op + data).repository
>>> print(repo)
Repository()
```
And it actually make sense is issues_alias is not defined in the class. But then again it raises the question is it possible to be still created as variable in the class instance with another name?

**Comment by barbieri** [comment]
It should. I’ll check. Did you try to access `repo.issue_alias`? Maybe it’s just missing in repr/str/dir

**Comment by lukavia** [comment]
I did, but with no luck, unfortunately:
```python
>>> print(repo.issue_alias)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Repository' object has no attribute 'issue_alias'
```

**Comment by barbieri** [comment]
@lukavia sorry it took me so long, but at the end it was a bug and I had to think how to solve it in a clean way. It's done since 9ef4b8a242772b9ee76acc5b958245428ff178b7, also added a helper to provide aliases in `__fields__(name='alias')` and an example usage.

Let me know if that fixes your usage, then I'll do a release.

Feel free to reopen if it's buggy.

**Comment by barbieri** [comment]
btw, as a reference the bug was that the Selection wasn't propagated to the children, so aliases happened to work... for the main query only :-P If you had another sub-object, a list... it wouldn't. To make things worse the non-null wrapper was also throwing the selection away (breaking the chain).

These are now fixed.

**Comment by lukavia** [comment]
Thank you very much!
It works perfectly.

**Comment by barbieri** [comment]
ok, did the release v4 and also took the time to publish the docs to https://sgqlc.readthedocs.io/ :-)
