### ISSUE TITLE
Option to require __typename

### ISSUE THREAD

**Issue by ThiloAschebrock** [profusion/sgqlc#175]
`__typename`s are currently added automatically when working with fragments, but there are use cases where you want to add `__typename` to all objects in a query, even if it is not defined by a fragment. I currently don't see any option to do so, even when manually constructing the query.

Could you either add the possibility to  include `__typename` into queries or enlighten me on how one could do it manually?

**Comment by barbieri** [comment]
@ThiloAschebrock took me a while, but the change did clean up some stuff. It's better located now and allows fragments (inline or named) to use `__fields__()`.

Take a look at the newest commits in that branch.

**Comment by ThiloAschebrock** [comment]
Hi @barbieri,

thank you very much for this improvement. It now works, i.e., I can select all fields and subfields of my mutation via:
```python
  operation = Operation(schema.Mutation)
  operation.my_mutation()
  operation.my_mutation.__fields__("__typename__")
  operation.my_mutation.field_with_union.__fields__("__typename__")
  for option in UnionTypes.__types__:
      option_fragment = Fragment(target, str(option))
      option_fragment.__fields__("__typename__")
      operation.my_mutation.request.field_with_union().__fragment__(option_fragment)
```
It's not optimal, as I have to provide the field with the union explicitly, but is sufficient for me.

**Comment by barbieri** [comment]
auto-selection should do this loop for you, did you try to just select `my_mutation.field_with_union`?

**Comment by ThiloAschebrock** [comment]
Yes, but this will not include `__typename` and not select any sub fields that are objects.

**Comment by barbieri** [comment]
Did you test it with the newest version? At least in the doctests this is the case. If you have a sample schema (or use GitHub) and a query that has the issue, let me know.

```py
>>> op = Operation(Query)
>>> op.repository(id='repo1').issues.__fields__('__typename__')
>>> op
query {
  repository(id: "repo1") {
    issues {
      __typename
      number
      title
      body
      reporter {
        __typename
        login
        name
      }
      assigned {
        __typename
        ... on User {
          login
          name
        }
        ... on Assignee {
          email
        }
      }
      commenters {
        __typename
        actors {
          __typename
          login
        }
      }
    }
  }
}
```

**Comment by ThiloAschebrock** [comment]
Try to add fields that are objects or even union of objects on the fragments and you will see that these fields will not be included with this solution.

**Comment by ThiloAschebrock** [comment]
@barbieri Would you mind releasing a new version that includes the corresponding PR?

**Comment by barbieri** [comment]
@ThiloAschebrock I'll do the release, but first if you can change an example (say `examples/github/list_issues.py`) or create a synthetic example, I may not be understanding the problem, to me looks like it works.
