### ISSUE TITLE
Instrospection schema not considered as one by the sgqlc-codegen command

### ISSUE THREAD

**Issue by R0hm** [profusion/sgqlc#180]
Hey guys,

The sgqlc-codegen command does not manage to generate the schema types file based on the instrospection schema obtained from [here](https://api.sorare.com/graphql/playground).

The schema does not have the fields `load_schema`is looking for, but the information needed seems to be there in other keys. Is it because this introspection file does not follow a standard ?

**Comment by barbieri** [comment]
If you have access, try to run the introspection query, you can do this with our tool or just copy & paste the query from https://github.com/profusion/sgqlc/blob/master/sgqlc/introspection/__init__.py

Looking at their download, it's a strange format I never faced. Some of the fields are prefixed with `_`, such as `_queryType` instead of `queryType`...there is also a `_typeMap`... looks like they just serialized a parsed DSL, which is not what people often call "introspection".

**Comment by R0hm** [comment]
I tried that yesterday:

`py -m sgqlc.introspection --exclude-deprecated https://api.sorare.com/graphql schema.json`

and received:

`ERROR: https://api.sorare.com/graphql: HTTP Error 403: Forbidden`

I didn't know what to put in that part of the command `-H "Authorization: bearer ${TOKEN}"` so maybe it is what gets me the forbidden access code :sweat_smile:

**Comment by R0hm** [comment]
Ok I managed to manually run the introspection query in the playground though, and it looked more like what your codebase expected. I then successfully run the sgqlc-codegen command 👍 

Can't wait to try your library now 🙂 

> I didn't know what to put in that part of the command -H "Authorization: bearer ${TOKEN}" so maybe it is what gets me the forbidden access code 😅

I'd be really curious to know what I was suppose to put in that authorization header part, I did not understand it very well, any chance you could help me with that ?

**Comment by barbieri** [comment]
did you manage to get it working? The `Authorization:` header is not the same in every service... usually it's like I said and you need an `accessToken` to be provided by some mean (ie: in the GitHub you can create one in the project/user settings, sometimes you need to execute an oAuth2 flow...) Some services may use standard basic/digest authentication... you need to check with your service provider.

**Comment by R0hm** [comment]
Yeah, following your advise, I ran the introspection query on the server and what I obtained looked like what your library expected.  With this result I was then able to properly run the `sgqlc-codegen` command, so thanks 👍 I guess the issue can be close.

PS : This is from what I remember, I did not play with Python and your library for some time now unfortunately...
