### ISSUE TITLE
Question: how to use the project with my local proxy

### ISSUE THREAD

**Issue by miyuki-shirogane** [profusion/sgqlc#183]
Love the project, it's very impressive.But i was wondering how do I use the project with my local proxy(like mitmproxy)?At the beginning,I thought it might be set in the class `HTTPEndpoint`,but I was failed to find it.
```
def __init__(self, url, base_headers=None, timeout=None, urlopen=None,
                 method='POST'):
```

**Comment by barbieri** [comment]
@miyuki-shirogane usually the libraries we use understand env vars such as `http_proxy` and `https_proxy`. You may also set-up transparent proxy using iptables and transparently route all outgoing traffic to some ip/port to mitmproxy.

By default we use [urllib.request](https://docs.python.org/3/library/urllib.request.html#urllib.request.urlopen), and you can see in the docs.

Alternatively you may use https://github.com/profusion/sgqlc/blob/master/sgqlc/endpoint/requests.py and read https://docs.python-requests.org/en/latest/user/advanced/#proxies

**Comment by miyuki-shirogane** [comment]
@barbieri  I have solved it, Thanks！
