### ISSUE TITLE
AttributeError: 'GraphQLToPython' object has no attribute 'enter_leave_map'

### ISSUE THREAD

**Issue by noa-upstream** [profusion/sgqlc#186]
Hi, 
After successfully generated the schema.py file,  I am trying to use  "sgqlc-codegen operation"
 but I am getting the following error:

AttributeError: 'GraphQLToPython' object has no attribute 'enter_leave_map'

Any thoughts on it?

**Comment by noa-upstream** [comment]
you are right, when I uses 'pip install sgqlc', graphql-core 3.2.0 were installed, I changed it and it fixed the problem.
Thanks @barbieri

**Comment by barbieri** [comment]
ok, are you sure it was 3.2.0? If that's the case then I need to make it compatible :-( usually that crash is with 2.x versions

**Comment by noa-upstream** [comment]
yes, it was 3.2.0 :/

**Comment by barbieri** [comment]
@noa-upstream this should be fixed in `master`, if you need to use 3.2.0 that should work. I'll do a release later
