### ISSUE TITLE
Generated github v4 API fails to import

### ISSUE THREAD

**Issue by hwine** [profusion/sgqlc#22]
Just starting out, and trying example from ``README.rst``. Introspection and code generation complete without error, however the generated file can't be imported:
```python
$ python
Python 3.6.4 (default, Feb 14 2018, 17:13:45)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from sgqlc.operation import Operation
>>> from github_schema import github_schema as schema
Traceback (most recent call last):
  File "/tmp/sgqc/.venv/lib/python3.6/site-packages/sgqlc/types/__init__.py", line 1565, in __populate_field_data
    value = json_data[graphql_name]
TypeError: string indices must be integers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/sgqc/github_schema.py", line 2077, in <module>
    class Query(sgqlc.types.Type):
  File "/tmp/sgqc/github_schema.py", line 2161, in Query
    ('order_by', sgqlc.types.Arg(SecurityAdvisoryOrder, graphql_name='orderBy', default=SecurityAdvisoryOrder('{field:"UPDATED_AT",direction:"DESC"}'))),
  File "/tmp/sgqc/.venv/lib/python3.6/site-packages/sgqlc/types/__init__.py", line 1538, in __init__
    self.__populate_fields(json_data)
  File "/tmp/sgqc/.venv/lib/python3.6/site-packages/sgqlc/types/__init__.py", line 1553, in __populate_fields
    self.__populate_field_data(field, field.type, None, json_data)
  File "/tmp/sgqc/.venv/lib/python3.6/site-packages/sgqlc/types/__init__.py", line 1571, in __populate_field_data
    self.__class__, name, value, exc)) from exc
UnboundLocalError: local variable 'value' referenced before assignment
```

**Comment by barbieri** [comment]
will take me few days to look into this. clearly 2 bugs :-)

the first one, `json_data` should be an object, not sure why it's a string...

**Comment by barbieri** [comment]
ok, the bug is in my handling of `defaultValue` for input types, I expect a dict (JSON Object), while the API gives me a string that must be parsed. I think it's better to parse and convert this to a dict at the codegen, keeping the import faster with pre-parsed JSON, but it's not so simple to do as I don't have the GraphQL parser myself, instead I relied on the JSON schema... maybe I'll need to depend on the upstream graphql parser :-/

**Comment by barbieri** [comment]
@hwine fixed in the latest `master` branch, please reopen if it doesn't solve your problems.

Confirm it's working for you, so I'll likely release a new version with that fix

**Comment by hwine** [comment]
@barbieri Works for me -- thanks for the quick fix!
