### ISSUE TITLE
Getting agrs values from Operation object

### ISSUE THREAD

**Issue by SShatun** [profusion/sgqlc#27]
Hello is there way to get the argument values from generated Operation object?
For example: 
```
>>> op = Operation(Query)
>>> repository = op.repository(id='repo1')
>>> repository.issues.number()
number
>>> repository.issues.title()
title
>>> op # or repr(), prints out GraphQL!
query {
  repository(id: "repo1") {
    issues {
      number
      title
    }
  }
}
```

If I use  `op`  in other class, how can i acces the repository id value object?

**Comment by barbieri** [comment]
you can use `repository.__args__`

problem is if you just get the `op`, then you can't easily fetch the "arguments of selection named 'repository'".

What you can do is iterate the `op` until you find the `repository` and then get its `__args__`. If order is fixed, you can use this:

```
repository = list(op)[0]
print(x.__field__, x.__args__)
```

**Comment by barbieri** [comment]
@SShatun does this answer/help? If it does then I'll close the issue.

**Comment by SShatun** [comment]
> @SShatun does this answer/help? If it does then I'll close the issue.

Yea, thank you!  
I made this method to get all arguments in query:

    ```
def __traverse_fields(self, fields: SelectionList):
        args = {}
        for field in fields:
            field_name = field.__field__.graphql_name
            args[field_name] = {'args': field.__args__}
            child_fields = field._Selection__selection_list
            if child_fields:
                args[field_name].update(**self.__traverse_fields(child_fields))
        return args
```

**Comment by barbieri** [comment]
your traverse function may conflict if any member/child is called `args`.

Moreover, what's the idea/need behinds this? I can try to come with an iterator...

**Comment by SShatun** [comment]
> function may conflict if any member/child is called args.
It is can be named like `__args` 

I'm using it for testing api. Sometimes I need to access all query arguments to check the response. It is looks like: 
Generate query with args -> send request -> get args from query -> make request to database with this args -> compare results.
So I'm getting args like this now:
`repo_id = op.get_args()['repository']['args]['id']`
Not so easy but better than store query arguments in special variable.

**Comment by barbieri** [comment]
hum... for testing, isn't it better yo simple serialize to string (with `str()` or `__to_graphql__()`) and check the string? At least it will be very simple to compare and write.

**Comment by SShatun** [comment]
So, then I will have to parse string to get the arguments. I need to compare response data (in case of query request) or changing data in db (in case of mutation) with excpected

**Comment by barbieri** [comment]
oops, I previously understood you had to check the query!

Ok, so what need is something else. I'll think about it.

**Comment by barbieri** [comment]
@SShatun added `Selectors.__selection__` so you can do the following:

```
op.repository.__selection__().__args__['id']
```

That is, `op['repository']` or `op.repository` will give you the *Selector*, which can contain multiple selections (using alias). If not using alias, it may be `None` (default). With that, the selection is returned and with it you can query `__alias__`, `__args__` or `__field__`.

**Comment by SShatun** [comment]
@barbieri it's looks good! 
But I can't try it cuz of [this](https://github.com/profusion/sgqlc/issues/30) 
Problem in my environment maybe

**Comment by SShatun** [comment]
It would be cool if I could to avoid the __selection__() calling to acces the __args__['id']
Like `op.repository.__args__['id']`
Looks mutch more simple, I think

**Comment by barbieri** [comment]
Done in a6cd8a345e73ee4eb7bd515d46ea3ecb3002064d

**Comment by SShatun** [comment]
Awesome!
