### ISSUE TITLE
Generating union fields with one type

### ISSUE THREAD

**Issue by SShatun** [profusion/sgqlc#31]
In  sgqlc-codegen `def write_type_union`:
```
self.writer('''\
class %(name)s(sgqlc.types.Union):
    __schema__ = %(schema_name)s
    __types__ = (%(types)s)
''' % {
            'name': name,
            'schema_name': self.schema_name,
            'types': ', '.join(v['name'] for v in t['possibleTypes']),
})
```

In case when only one type in Union it will generate code like this:
```
class UnionField(sgqlc.types.Union):
    __schema__ = gw_schema
    __types__ = (OneField)
```

But `(OneField)` is incorrect tuple. It is must be `(OneField,)`.

It solves with adding comma in `(%(types)s)` . Like `(%(types)s, )`. But it is looks not so good when types more than one: `(OneField, SecondField,) `. Still works fine but looks ugly.

Ofcourse it is uncommon case but possible.

**Comment by barbieri** [comment]
adding a trailing `,` is okay... can you send the patch?

and yeah, not so common!

**Comment by barbieri** [comment]
btw this may happen with enum as well, need to check

**Comment by SShatun** [comment]
Made [the patch](https://github.com/profusion/sgqlc/pull/33).
I think there should be no problems with enum cuz in that case using tuple formating:
`'choices': tuple(v['name'] for v in t['enumValues'])`

**Comment by barbieri** [comment]
used a different approach as in 704c8c2ac7b4d54c1fb48d826a2ed5cf16d231c3

thanks for your help!
