### ISSUE TITLE
unicode support

### ISSUE THREAD

**Issue by petpil** [profusion/sgqlc#32]
I had an issue with using strings containing non ASCII characters. I have german special characters like 'ü' and so on. I solved it by changing line 1192 in `types/__init__.py`
from: 
   `return json.dumps(cls.__to_json_value__(value))`
to:
   `return json.dumps(cls.__to_json_value__(value), ensure_ascii=False)`

Best regards
Peter

**Comment by barbieri** [comment]
not sure I get the bug, could you send/paste a testcase?

I'm Brazilian, so I'm used to non-ASCII letters and just tried it, it works. But you need to have UTF-8 contents. See:

```py
>>> import json
>>> json.dumps('á')
'"\\u00e1"'
>>> json.dumps('ü')
'"\\u00fc"'
```

**Comment by barbieri** [comment]
in the JSON spec you can have `\u<HEX>`, so here it's `\u` to say it's an unicode char with `0x00fc` (2 bytes) for umlaut-u.

**Comment by petpil** [comment]
The problem that I had, was that I sent a mutation to the server, which seemed to accept it, but didn't update the content. I got no error.
here is what my operation looks like with ensure_ascii:
`mutation {
  event_update(id: "event-378605811-22002071", lang: "DE", update_data: {place: "Renzenhof, N\u00fcrnberger Land, Bayern, Deutschland", header: "Innwohner"}) {
    id
    place
  }
}`

and this is what I then get as the response
`{'data': {'event_update': {'id': 'event-378605811-22002071', 'place': 'Renzenhof, Bayern, Deutschland'}}}`

As you can see the `place` is not updated. After I set ensure_ascii to False it works. It might be an issue of the server though but this is out of my bounds.

**Comment by barbieri** [comment]
Is this a public server I can test? Do you have its code and can fix there?

This looks like a server issue not doing proper JSON parse. Ex:

Node.JS
```
> JSON.parse('"Renzenhof, N\u00fcrnberger Land, Bayern, Deutschland"')
'Renzenhof, Nürnberger Land, Bayern, Deutschland'
```

Python 3
```
>>> import json
>>> json.loads('"Renzenhof, N\u00fcrnberger Land, Bayern, Deutschland"')
'Renzenhof, Nürnberger Land, Bayern, Deutschland'
```
Python 2 doesn't print encoded, but it's correct:
```
>>> import json
>>> json.loads('"Renzenhof, N\u00fcrnberger Land, Bayern, Deutschland"')
u'Renzenhof, N\xfcrnberger Land, Bayern, Deutschland'
>>> print(json.loads('"Renzenhof, N\u00fcrnberger Land, Bayern, Deutschland"', 'utf-8'))
Renzenhof, Nürnberger Land, Bayern, Deutschland
```

**Comment by barbieri** [comment]
anyway, added `__json_dump_args__` to the class, you can change that to force `ensure_ascii=False`. Let me know if it worked.

**Comment by petpil** [comment]
The server belongs a company called MyHeritage. That's the website describing their schema
www.familygraphql.com

I'll give your addon a try. Thanks for the prompt replies!
