### ISSUE TITLE
Using search query on GitHub API is missing top level map brackets

### ISSUE THREAD

**Issue by xster** [profusion/sgqlc#34]
I'm not familiar with GraphQL so this may be more or less coherent.

Suppose a top level query of:
```graphql
{
  search(first: 100, query: "blah", type:ISSUE) {
    nodes {
      ... on PullRequest {
        number
      }
    }
  }
}
```

using codegen against https://api.github.com/graphql and creating something to the effect of

```python
op = Operation(schema.Query)
prs = op.search(first=100, type=SearchType("ISSUE"), query="blah")
prs.nodes.__as__(schema.PullRequest).number()
```
etc produces an outgoing string that doesn't have top level brackets and results in 
```
GraphQL query failed with 1 errors
{'errors': [{'message': 'Parse error on "search" (IDENTIFIER) at [1, 1]', 'locations': [{'line': 1, 'column': 1}]}]}
```

Tweaking http.py's get_http_post_request to wrap the query with {} seems to make it work.

**Comment by xster** [comment]
Yup, that was totally incoherent. I endpoint'ed against the calls on the Operation rather than the Operation itself :S

**Comment by barbieri** [comment]
let me know if the docs are not that clear or more examples are needed, there is always room for improvements.

another option is to detect the type in runtime and navigate back to the parent operation, "hiding" such issues

**Comment by xster** [comment]
I guess you can assert that endpoint() is called on an Operation type rather than any other Field type to pre-emptively warn. 

Since you're being nice about this, I'm gonna harass you with another one :D https://github.com/profusion/sgqlc/issues/35
