### ISSUE TITLE
Converting to json

### ISSUE THREAD

**Issue by waystilos** [profusion/sgqlc#36]
I want to convert my query

```
query {
  friend(id: "randomnumbers") {
    name
    nickname
  }
}
 ```

to 

```
{ 'query': 
    '{ 
        friend(id: "randomnumbers) { 
              name 
              nickname
         } 
      }' 
}
 ```

I've been trying to go over the documentation but can't see any method that converts the query to json. Any help is appreciated! Thanks.

**Comment by barbieri** [comment]
There is no public way to assemble that particular json as it's specific for the HTTP, then it's done at https://github.com/profusion/sgqlc/blob/master/sgqlc/endpoint/http.py#L196

But you can get the `{ friend(id ...) ` (what goes as the `query` value) by calling one of the `Operation` methods:
 - `str(op)` - human friendly
 - `bytes(op)` - compact
 - `op.__to_graphql__(indent=0, indent_string='  ', auto_select_depth=2)`, see https://github.com/profusion/sgqlc/blob/master/sgqlc/operation/__init__.py#L1660

the first 2 are just shortcuts to call the `__to_graphql__()` with different parameters.

See if that helps you, but I wonder why not use the http endpoint.

On my todo list (but out of time to execute it) are:
 - asyncio's aiohttp.client
 - websockets

if you want one of them, try to do a patch, I can guide you and merge this in the project

**Comment by waystilos** [comment]
> but I wonder why not use the http endpoint.

I'm behind an internal gateway that has its own client library I have to use. I would totally use it if I could.

Thanks so much for the quick reply and the help. I'll give it a try tomorrow morning.

**Comment by barbieri** [comment]
you may choose to subclass that and change the request/open call

**Comment by barbieri** [comment]
is the provided solution (subclass endpoints) a good enough solution?

Do you still need support with this? Otherwise please close the issue :-)
