### ISSUE TITLE
operation kind issues

### ISSUE THREAD

**Issue by alogan-nyansa** [profusion/sgqlc#37]
I can't tell if this is our implementation of GraphQL doing something wrong or a bug/bad assumption in this library. 

In V5 of this library, in the operation \__to_graphql__ it was assumed that kind was either query or mutation. Now it takes the typ.\__name__.lower() and uses that as the kind. This causes issues because instead of the initial query just being query{} it is now the name of the class from introspection call, in this case, something like graphqlquery{}, and our system rejects it. If I rename the query class in the schema from graphqlquery to query, everything works. 

So I guess the main question is, should our system be accepting graphqlquery as the initial request instead of just query, or should there be an override for the kind somewhere?

**Comment by barbieri** [comment]
no, `graphqlquery` is not to be accepted by the protocol.

The idea to use the `__name__` was to be extensible and support `Subscription` and whatever else would be added to future GraphQL versions...

One question: why are you naming `GraphQLQuery`? Usually these schemas are auto-generated and placed in their own files, which guarantees the namespace for you and there is no need to encode in the name.

I see 2 alternatives to avoid the separate file, if you must keep it:

 - declare inside a narrow scope (ie: function) as `Query`, return the object and assign it to a variable with a different name
 - override `GraphQLQuery.__name__ = 'Query'`

none are beautiful solutions, but I'd recommend moving to its own file. If that's not a solution, let me know and I'll try to come with a cleaner alternative.

**Comment by alogan-nyansa** [comment]
The naming was received from the introspection query but doesn't appear to be accepted when I query. Below is the relevant class from the schema.py file. If I change GraphQLQuery to just Query, everything works happy, if I leave it as GraphQLQuery the GraphQL endpoint rejects it as a bad query. 


`class GraphQLQuery(sgqlc.types.Type):
    __schema__ = vapi2
    access_point_list = sgqlc.types.Field(sgqlc.types.non_null('AccessPointList'), graphql_name='accessPointList', args=sgqlc.types.ArgDict((
        ('search', sgqlc.types.Arg(String, graphql_name='search', default=None)),
        ('uuids', sgqlc.types.Arg(sgqlc.types.list_of(sgqlc.types.non_null(String)), graphql_name='uuids', default=None)),
        ('page_size', sgqlc.types.Arg(Int, graphql_name='pageSize', default=25)),
        ('page', sgqlc.types.Arg(Int, graphql_name='page', default=1)),
        ('sort_by', sgqlc.types.Arg(sgqlc.types.list_of(sgqlc.types.non_null(String)), graphql_name='sortBy', default=['lastUpdated'])),
        ('sort_order', sgqlc.types.Arg(SortingOrder, graphql_name='sortOrder', default='DESC')),
        ('from_date', sgqlc.types.Arg(Date, graphql_name='fromDate', default=None)),
        ('location_filter', sgqlc.types.Arg(sgqlc.types.list_of(sgqlc.types.non_null(String)), graphql_name='locationFilter', default=None)),
        ('filters', sgqlc.types.Arg(FieldFilters, graphql_name='filters', default=None)),
))
    )
`

**Comment by barbieri** [comment]
wow, is that generated from introspection? is it a public server I can check?

Following the spec what you sent is correct, you can declare a different type name (ie: `GraphQLQuery`), given that you declare a schema and do: `queryType: YourFancyNameHere`. As nobody I saw bother to change that, nobody declares the `schema` manually... so my shortcut did work, until now :-/

I'll think a bit if I go back to the old manual way to use `query` for everything that is not called `Mutation`, or if I introduce a new parameter that you'll explicitly state if it's a `query`, `mutation` or `subscription`.

That's why I'd like to see the introspection... very likely your case will need an explicit name, as if it follows the pattern, your Mutation would be called `GraphQLMutation`, etc.

while generating I could use the `__schema.queryType.name` to override what's used by the library... maybe it's a better solution. If you can send me the schema, it will help to decide.

**Comment by alogan-nyansa** [comment]
Yes, it is from introspection, no it isn't a public server. Let me see what I can do to get you a schema file for it.

**Comment by barbieri** [comment]
you can paste here just the `__schema` key from the resulting JSON... you can drop the directives part, just need the `queryType`, `subscriptionType` and `mutationType`

**Comment by alogan-nyansa** [comment]
`{
  "data": {
    "__schema": {
      "directives": ["bunchofstuffherethatideleted"],
      "mutationType": null,
      "queryType": {
        "name": "NyansaGraphQLQuery"
      },
      "subscriptionType": null,
      "types": ["bunchofstuffherethatideleted"]
    }
  }
}`

Here you go.

**Comment by barbieri** [comment]
i'll need some time to get back to sgqlc development (will try to do this wednesday), meanwhile if you can:
- force `.__name__ = 'Query`
- rename the generated file to use `Query`

you can get going, ok?

**Comment by alogan-nyansa** [comment]
Understood. I am creating a primer application that we can give to our users so they can easily pull data from our platform. I created a pure python file that skips the JSON output and just takes the requisite inputs and creates the schema without the intermediate json file steps so people can update easily when we add new things to our API. Once I get some windows users to test it, I will create a clean version and add it to a fork for you to take a look at. 

I am good for now by just editing the schema file to reflect Query. I am good for now until I start distributing. Thanks for all your work on this library.

**Comment by barbieri** [comment]
could you confirm 6bb379a58321810b7ebc6b884c340197a274ffa9 fixed it?

**Comment by ian-h-chamberlain** [comment]
@barbieri – I am not the OP but I ran into this same issue when I upgraded from 5.0 (or 6.0 when I tested) to 7.0. When I installed `sgqlc` from `master` it worked without a problem, and I can see when I manually declare a schema that setting the `query_type` has the same effect.

Any chance a version with this change this will be published as 7.1? I can keep using 6.0 in the meantime.

**Comment by barbieri** [comment]
@ian-h-chamberlain could you confirm this patch fixes it? I'm about to release a new version that will include it

**Comment by ian-h-chamberlain** [comment]
Yes, when I install `sgqlc` at 6bb379a (or `master`) the generated module works as expected (`query {...}` in the output even though the generated class is named `RootQuery` in my case. I see the generated output includes `query_type`:
```
mod.query_type = RootQuery
mod.mutation_type = RootMutation
mod.subscription_type = None
```

Thanks for the fix!

**Comment by barbieri** [comment]
release https://github.com/profusion/sgqlc/releases/tag/v8.0 and uploaded to pypi includes this fix.

**Comment by krakenant** [comment]
@barbieri confirmed fixed for me as well, Thanks!
