### ISSUE TITLE
total_count is not a standard field

### ISSUE THREAD

**Issue by sebastiandev** [profusion/sgqlc#39]
The library is expecting relay.connection objects to have a `total_count` [here](https://github.com/profusion/sgqlc/blob/master/sgqlc/types/relay.py#L364), but that is not a standard field. Graphene for example doesn't implement it, and is not defined either in https://facebook.github.io/relay/graphql/connections.htm

If anyone implemented it it would be picked up from the introspection I guess, so no need to make it a default field in the connection.

**Comment by barbieri** [comment]
currently busy with work, I'll try to tackle this together with the other open issues ASAP.

Patches are welcome, this one should be a matter of deleting the lines

**Comment by barbieri** [comment]
closed with #40
