### ISSUE TITLE
Example for all fields of an inline fragment?

### ISSUE THREAD

**Issue by Elektra58** [profusion/sgqlc#43]
Does anybody have an example of using **all** fields of an inline fragment and setting a parameter for one of them?

The examples show the use of selecting an individual field:
`` 
op = Operation(Query)
repo = op.repository(id='repo1')
repo.owner().__as__(Organization).location() # location field for Orgs
``
What if my ActualType had many fields (and might get more in the future) and I can't manually add them all?

It might be helpful to add this to the basic example. Thank you!

**Comment by barbieri** [comment]
will look into this soon, but the idea of GraphQL is to always select what and only what you use.

The helpers to auto-select all fields described in a type is to ease development/debug, not for production usage as it could "leak" fields, bringing information that is not desired.

That said I'm not sure I handle the case of auto-selection after the field is already selected. I'm pretty sure the other way -- selecting all + individual field -- around is a no-go (it would result in the same field being selected twice with the same alias and different parameters).

**Comment by Elektra58** [comment]
The helper to select all fields does indeed come in handy for development and debugging, and I use it for all types that are not fragments. I exlude the field that has a parameter and then add it again. This works beautifully. 

I have an API with many longer fragments, so adding all existing files manually is painful and messes up the code, so I thought I just did not get it how to do it with fragments. Leakage of new files might not be that much of a problem because I downloaded the schema through insomnia and then used your code generator to generate all the classes. Great work!

**Comment by barbieri** [comment]
sorry taking so long!

looked into this and my recommendation:

```py
some_selection.__fields__(__exclude__=('what_you_want_to_add_args',))
some_selection.what_you_want_to_add_args(arg='value')
```

**Comment by barbieri** [comment]
this is a bit more verbose, but is clear and I don't need to add any other logic to the already too-complex code.

Also take my recommendation to just select what you use!

**Comment by Elektra58** [comment]
Thanks. Figured it out. For exploring an API I use Insomnia and then build the logic in Python as you described.
