### ISSUE TITLE
HTTPEndpoint.__call__ replaces 'Accept' header

### ISSUE THREAD

**Issue by hrez** [profusion/sgqlc#49]
HTTPEndpoint.__call__ forces 'Accept' header thus preventing setting github preview schemas such as "application/vnd.github.echo-preview+json" etc.

I suggest setting it only if absent like:
if 'Accept' not in headers:
            headers.update({
                'Accept': 'application/json; charset=utf-8',
            })

**Comment by barbieri** [comment]
We can use `headers.setdefault('Accept', 'application/json; charset=utf-8')`

I'll take a look as soon as I have time.

**Comment by barbieri** [comment]
closed by #54
