### ISSUE TITLE
When mutation takes a list as an argument - passing in a list of the type does not work

### ISSUE THREAD

**Issue by kshehadeh** [profusion/sgqlc#53]
I have an input type that takes a list as an argument.  I haven't seen an example of this use case so I just guessed that I could pass in a python list of the right type.  But I get the following error:

`AttributeError: 'MyInput' object has no attribute 'items'`

And, in fact, it is expecting a dict.  Here's an edited version of the code I use to run the mutation:

    list_arg = [
        gql.MyInput({"key1":"val1"})
        gql.MyInput({"key1":"val2"})
    ]

    op.my_mutation(my_list=list_arg)

I'm assuming that passing a simple list into the argument is not the right way to go about it, but I'm not sure how to construct the list otherwise.

Thoughts?

**Comment by barbieri** [comment]
I think this suffers from the same problem as #42. I never gave input arguments the deserved love.

I'm under a heavy work load, I'll try to address this once I look at #42.

If you have some time to help, patches are more than welcome!

**Comment by kshehadeh** [comment]
Great! I just wanted to make sure I wasn't doing something wrong.  I'll see about if I can address.

**Comment by barbieri** [comment]
Passing explicit input objects should work, but seems it is not working as expected to create them. However it would be super-handy to allow plain Python objects to be used -- after all the GraphQL input types are as simple and we could convert easily.

So I'd suggest:
 - check the input object constructor. Unlike the output types, you're not receiving a JSON dict from the server... the developer/user is typing them, thus using `**kwargs` would make sense, allowing `gql.MyInput(key1="val1")` in your case.
 - get the argument type and with it auto-convert from plain python types -- so `{"key1":"val1"}` would result in `gql.MyInput(**{"key1":"val1"})`.
 - do it recursively, so lists and nested objects works.

**Comment by barbieri** [comment]
could you confirm b1c740cf77c50fbbc05bdf71bc7fa3543fb15017 fixed it?

**Comment by barbieri** [comment]
note: https://github.com/profusion/sgqlc/releases/tag/v8.0 and uploaded to pypi!

it should include this fix, let me know if solves this issue

**Comment by kshehadeh** [comment]
Thank you!!
