### ISSUE TITLE
Introspection overrides Accept header

### ISSUE THREAD

**Issue by 8032** [profusion/sgqlc#59]
Related to https://github.com/profusion/sgqlc/issues/49

When making queries to the GitHub API to use the VulnerabilityAlerts it is necessary to specify a custom Accept header.

When specifying on the `HTTPEndpoint` it is overridden so the header cannot be specified.

Change the behaviour to add if it doesnt exist.

**Comment by barbieri** [comment]
good point, can you send a patch as well?

**Comment by 8032** [comment]
PR created https://github.com/profusion/sgqlc/pull/60
