### ISSUE TITLE
PyPi Version

### ISSUE THREAD

**Issue by mike-sosa-sofarocean** [profusion/sgqlc#63]
Hi, was wondering if there was a plan/development schedule for releasing updates on PyPi? The last update on PyPi was in February and it seems a bit out of date.

**Comment by barbieri** [comment]
yes, I planned to do this weekend, I'll try to do it today

**Comment by barbieri** [comment]
done: https://github.com/profusion/sgqlc/releases/tag/v8.0 and uploaded to pypi!

**Comment by mike-sosa-sofarocean** [comment]
Awesome. Thank you!!
