### ISSUE TITLE
HTTPEndpoint utilising requests instead of urllib

### ISSUE THREAD

**Issue by strazeadin** [profusion/sgqlc#69]
Hello,

I'm looking to utilise sgqlc for communicating between AWS Lambda functions and AWS AppSync. In order to support this workflow I need to be able to authenticate my HTTP Requests using [SigV4](https://docs.aws.amazon.com/general/latest/gr/signature-version-4.html) and that currently isn't supported with the existing HTTPEndpoint.

I'm looking to get your opinion in regards to contributing either a separate or modified version of the existing HTTPEndpoint that utilises the Requests library. That will allow usage of [authentication with Requests](https://requests.kennethreitz.org/en/master/user/authentication/) and doesn't require large amount of code changes. (I already have a working version)  

Keen to get your opinions on the matter as I would like to see if you see value in this for other users.

**Comment by barbieri** [comment]
I'd like to keep `HTTPEndpoint` simple and without extra deps for ease of use.

However I see the reason to support others, like we have WebSocket that uses a third party library as optional dep. Could you write another `RequestsEndpoint` or the like that will use the requests library?

if needed you can split common parts in the `base.py` file.

Another option is to write an `urlopen()`-like function that internally uses `requests`, then you could pass it to `HTTPEndpoint`.
