### ISSUE TITLE
Unable to resolve fields on Union types

### ISSUE THREAD

**Issue by johnjstuart** [profusion/sgqlc#71]
Recently I ran into something that appears to be either a bug or missing functionality where creating query selections on union types doesn't work properly.

This example throws a `AttributeError: TypeA has no field name`:
```Python
import sgqlc
from sgqlc.operation import Operation
from sgqlc.types import String, Type, Union, Field, non_null


class TypeA(Type):
    i = int

class TypeB(Type):
    s = str


class TypeU(Union):
    __types__ = (TypeA, TypeB)


class Query(sgqlc.types.Type):
    some_query = Field(non_null(TypeU), graphql_name='someQuery')


op = Operation(Query, name="op_name")
q = op.some_query()
q.__fields__()  # this line throws 'AttributeError: TypeA has no field name'

```

If I modify `TypeA` to have a `name` field:

```Python
class TypeA(Type):
    i = int
    name = str
```

I then get this error: `KeyError: name: String` from the same line as the above error.

It seems that field selection on Union types might be broken. If I omit `q.__fields__()` it will generate the correct query string, but then the fields are not deserialized and added to the resulting object when interpreting the result:

```Python
op = Operation(Query, name="op_name")
op.some_query()  # don't select any fields

data = {"data": {
    "someQuery": {
        "__typename": "TypeA",
        "i": 1234,
        "name": "name",
    }
}}

result = op + data  # result = TypeA()
```

Am I missing some kind of special syntax for Union types that I couldn't find in the documentation or is this just not working as it should?

**Comment by barbieri** [comment]
While the error is misleading (I should fix that), in GraphQL you can't select fields of an union type directly, you must use fragments to select depending on each type you want to handle.

In your case, could you try:

```py
op = Operation(Query, name="op_name")
q = op.some_query()  # don't select any fields
q.__as__(TypeA).i()
```

https://sgqlc.readthedocs.io/en/latest/sgqlc.operation.html#inline-fragments-interfaces

**Comment by johnjstuart** [comment]
Okay, that makes sense. I didn't find that piece of documentation when searching for Union types. I'll give it a shot tomorrow. It might be helpful to add `Union` to the heading and description to make it easier to find the docs for it. Thanks for the help!

**Comment by johnjstuart** [comment]
@barbieri Gave it a shot this morning and now everything works. I did notice though that you can't use `.__as__(Type).__fields__()` I think it would be pretty useful to be able to select all fields on a fragment like this. That might be a nice feature to add in the future.

**Comment by barbieri** [comment]
I'll take a look to see if `__fields__()` can be implemented, I don't recall if it was something that I couldn't solve or if I just forgot.

However keep in mind that `__fields__()` is an anti-pattern for GraphQL, I added it as a helper to aid scripts and quick hacks, it goes against GraphQL principle to just select what you use.

**Comment by johnjstuart** [comment]
@barbieri good point about the anti-pattern. I do sometimes prefer to use `obj.__fields__(*args)` where `*args` is a list of string field names, instead of calling each field on `obj` individually because it's much less verbose. `__fields__(__exclude__=*args)` is also a good use case for keeping `__fields__()` in the API and doesn't seem like an anti-pattern to me. These are both especially helpful when there are a lot of queries that require the same fields on a given type.

**Comment by barbieri** [comment]
yeah, I'll try to see why the `__fields__()` isn't working on the `__as__(TypeHere)`, but quite busy with work these days :-(

**Comment by barbieri** [comment]
@johnjstuart sorry taking many years to do this, not sure if you still uses sgqlc or not (let me know!), but it's finally done in #176 along other improvements.
