### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by Jut254** [profusion/sgqlc#73]
I'm getting this error when I'm calling a specific query within my sgqlc schema? Is there anything inherent within this package that could case that error? I only get the error with a specific query that I am doing, other queries work just fine.  
  
I can post the schema .py file if that would help.

**Comment by barbieri** [comment]
given the look seems the server was written in JavaScript (ie: Apollo) and was sending you an internal error, such as: 

```js
myFieldResolver: (obj, args) => {
   const someHandle = findSomeHandle(obj, args);
   // suppose someHandle wasn't found, thus "undefined"
   return someHandle.length;
}
```
was that the case?
