### ISSUE TITLE
ImportError: cannot import name 'Value' from 'graphql.language.ast'

### ISSUE THREAD

**Issue by ivica-k** [profusion/sgqlc#74]
Hello and thank you for this library.

I encountered an issue when trying to generate Python code from a known GraphQL schema using the tool you provided. Simply running it without any inputs produces:

```
sgqlc-codegen 
Traceback (most recent call last):
  File "MY/VENV/PATH/bin/sgqlc-codegen", line 12, in <module>
    from graphql.language.ast import Value as GraphQLASTValue
ImportError: cannot import name 'Value' from 'graphql.language.ast'
```

I have `sgqlc` `v9.0` installed locally. If I can provide any more info please don't hesitate to ask.

**Comment by NickHilton** [comment]
@ivica-k - Before this PR gets merged you or we decide on a different fix, you can `pip install -e git://github.com/NickHilton/sgqlc.git@graphql-explicit-version#egg=sgqlc` (i.e. the branch from that PR) to get sgqlc working again in your project

**Comment by barbieri** [comment]
See if efa0269d338b4bd4fda21e9aa1167b44f66d7325 fixed it

**Comment by barbieri** [comment]
Released as https://pypi.org/project/sgqlc/9.1/ see if fixes the issue, if so then close.

**Comment by ivica-k** [comment]
Thank you for a very quick response and fix. Will look into it tomorrow most probably.

**Comment by barbieri** [comment]
could you verify? I think it's fixed now.

**Comment by ivica-k** [comment]
Works like a charm, sorry for not replying earlier. Thank you very much for a quick fix.
