### ISSUE TITLE
sgqlc.endpoint.requests.RequestsEndpoint has no way to pass `verify=False`

### ISSUE THREAD

**Issue by jacobbogdanov** [profusion/sgqlc#76]
Hi,

As of PR #70  there is support for a `requests` endpoint (which is awesome!) but there is no way to pass some of the extra arguments that [`requests.request()`](https://requests.readthedocs.io/en/master/api/#requests.request) supports.

In this case I would like to add `verify=False`, which is forwarded to `requests.Session.send`.

**Comment by jacobbogdanov** [comment]
There is actually another similar problem I ran into:

I am trying to use [`requests_unixsocket`](https://github.com/msabramo/requests-unixsocket) which has a `requests_unixsocket.monkeypatch()` method to patch `requests` to support HTTP over a socket. However the way that `requests_unixsocket` package patches `requests` is incompatible with `RequestsEndpoint` as it creates a `requests.Session` itself for each invocation of `RequestsEndpoint.__call__`.

I think a possible solution to both of these problems is to have `RequestsEndpoint`'s constructor accept a session cls. For the `verify=False` problem, I as a user, could create a simple `Session` of my own:
```python
import functools
import requests

class MySession(requests.Session):
    def __init__(self):
        super().__init__()
        self.send = functools.partial(requests.Session.send, verify=False)
```

This would solve both problems as I'd just create a `RequestsEndpoint` using either

```python
unverified_endpoint = RequestsEndpoint(..., session=MySession)
socket_endpoint = RequestsEndpoint(..., session=requests_unixsocket.Session)

**Comment by barbieri** [comment]
i think we can use the constructor `RequestsEndpoint()` to take an existing session or `None` and then keep using it on further calls (`__call__`). Then the `Session` would be created on the **constructor** (`__init__`) rather than on call.

It does change the behavior a little bit since connections could be reused and cookies would be taken/sent, but I believe this behavior is better than re-creating it every time.

Could you submit this patch?

**Comment by barbieri** [comment]
another (not exclusive) option is to add more arguments to the `__call__()`, in addition to `timeout` we could pass `verify`, `proxies` and `cert`.

**Comment by jacobbogdanov** [comment]
I can work on submitting a patch.

I think I've convinced myself that sharing a session instance makes sense here, especially because it's the same endpoint between calls.

As far as adding `verify`, `proxies`, and `cert` is there any reason to take them in `__call__` over the constructor?
I see that `timeout` is actually accepted in both, but for these new three I can't think of a reason someone would want to change them between invocations of `__call__`.

**Comment by barbieri** [comment]
me neither, it was just an option, but I don't see the need to change them per-call... but it would match the requests lib, where you can set the session or the fetch.

**Comment by alogan-nyansa** [comment]
I fixed this myself by adding verify as an option to __call__ with a default of True. Any issues if I add this to the main branch?

**Comment by barbieri** [comment]
that's ok, please send the PR (just be sure to pass the flake8, it's in the utils/git/pre-commit) and send on top of the latest master.

**Comment by moorereason** [comment]
A PR has been merged that should allow the use of a custom `requests.Session`.  @jacobbogdanov, does that solve your issue?
