### ISSUE TITLE
Fields beginning with '_' are ignored

### ISSUE THREAD

**Issue by plorenzatto** [profusion/sgqlc#81]
I'm currently using the schema generated by codegen to consume the hasura endpoints.
Some of them use fields like `_and`, `_eq`, etc to represent different operators [1].

The problem I'm having is that when trying to instantiate an object with one of this attributes I get the following exception:
```
>>> schema.someobject_bool_exp(_and=1)
Traceback (most recent call last):
  File "/home/user/miniconda3/lib/python3.6/site-packages/sgqlc/types/__init__.py", line 1557, in __getitem__
    return cls.__fields[key]
KeyError: '_and'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/miniconda3/lib/python3.6/site-packages/sgqlc/types/__init__.py", line 2449, in __init__
    f = cls[k]
  File "/home/user/miniconda3/lib/python3.6/site-packages/sgqlc/types/__init__.py", line 1559, in __getitem__
    raise KeyError('%s has no field %s' % (cls, key)) from exc
KeyError: 'address_details_bool_exp has no field _and'
```
The error seems to be product of the following condition in ContainerTypeMeta [2]:
```
    def __create_own_fields(cls):
        [...]
        for name in members:
            if name.startswith('_'):
                continue
```
The workarounds I found are:
- Adding a whitelist to the condition of permitted exceptions to the rule for the fields I need (bad).
- Renaming the affected field (`_and` => `op_and`).

What failed:
- Removing the condition break the code elsewhere.

What might be a better solution:
- Check if attributes starting with `_` belong only to the child class but not the parent.
- Make the codegen add a prefix to all fields begining with `_`.

Ref:
[1]: https://docs.hasura.io/1.0/graphql/manual/queries/query-filters.html#comparision-operators
[2]: https://github.com/profusion/sgqlc/blob/ef07ebb5692756e2531a4bf2119ecbd611e8e6d9/sgqlc/types/__init__.py#L1527

**Comment by barbieri** [comment]
I think we'll need to alias the fields in sgqlc-codegen to prefix (but that itself may lead to other issues, like clashes with existing names) or add a `__field_names__ = ('_and', '_or')` for fields that exist in the schema, codegen would add all the names in there and the code would take a different path instead of introspection of the current class -- the existing code would be left as fallback for people manually declaring classes.

could you implement this? otherwise it may take me a while to free some time to do it :-(

**Comment by plorenzatto** [comment]
I need this working so I'll probably submit a PR later on.

Adding a `__field_names__` attribute sounds like a good solution.

IUC that would also require changing the condition mentioned before and adding a default value to `__field_names__` in `ContainerTypeMeta`.
```python
    if name.startswith('_') or name in cls.__field_names__:
```
Is that right?

**Comment by barbieri** [comment]
@plorenzatto I think we can use only `__field_names__` if that is set, this will be the case with `codegen` and with that we'd get a very minor speedup since we could skip `dir()` + `if name.startswith('_')` altogether...
