### ISSUE TITLE
Error in generated Hasura schema

### ISSUE THREAD

**Issue by Nabu-thinker-ru** [profusion/sgqlc#82]
Greetings!

Importing generated from attached [json](https://github.com/profusion/sgqlc/files/4025204/rx_schema.txt) schema fails with this traceback:

`Traceback (most recent call last):
  File "/home/vagrant/venv3.8/lib/python3.8/site-packages/sgqlc/types/__init__.py", line 847, in __ensure__
    return map_python_to_graphql[t]
KeyError: country(
    distinct_on: [country_select_column!]
    limit: Int
    offset: Int
    order_by: [country_order_by!]
    where: country_bool_exp
  ): [country!]!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vagrant/src/read_grls.py", line 10, in <module>
    from api import CountryManager
  File "/home/vagrant/src/api.py", line 4, in <module>
    from rx_schema import rx_schema as schema
  File "/home/vagrant/src/rx_schema.py", line 301, in <module>
    class query_root(sgqlc.types.Type):
  File "/home/vagrant/src/rx_schema.py", line 319, in query_root
    country_by_pk = sgqlc.types.Field(country, graphql_name='country_by_pk', args=sgqlc.types.ArgDict((
  File "/home/vagrant/venv3.8/lib/python3.8/site-packages/sgqlc/types/__init__.py", line 2293, in __init__
    super(Field, self).__init__(typ, graphql_name)
  File "/home/vagrant/venv3.8/lib/python3.8/site-packages/sgqlc/types/__init__.py", line 1933, in __init__
    self._type = BaseType.__ensure__(typ)
  File "/home/vagrant/venv3.8/lib/python3.8/site-packages/sgqlc/types/__init__.py", line 849, in __ensure__
    raise TypeError('Not %s or mapped: %s' % (cls, t)) from exc
TypeError: __str__ returned non-string (type NoneType)`

sgqlc==9.1.dev20200104
Hasura v1.0.0

**Comment by chedburgh** [comment]
I have the same problem with a schema introspected from Hasura and then code generated with sgqlc-codegen. I cloned the repo 2020-01-12 for the latest dev version.

Any ideas or pointers that may help? I am pretty new to the project/graphql and this is blocking me.

Thanks in advance.

**Comment by barbieri** [comment]
a quick look into it, nothing clear... will take me some time to investigate what's going on.

**Comment by barbieri** [comment]
I couldn't fix it yet, but seems a problem with resolving/referencing `country`. If I replace those using lazy (with quotes), it passes.

It's strange as it's defined in a very simple way:

```py
class country(sgqlc.types.Type):
    __schema__ = rx_schema
    id = sgqlc.types.Field(sgqlc.types.non_null(Int), graphql_name='id')
    name = sgqlc.types.Field(sgqlc.types.non_null(bpchar), graphql_name='name')
```
this shouldn't bring any circular dep or the likes, later i'll try to investigate what's going on... :-(

**Comment by barbieri** [comment]
I hope I've solved your issue, seems to work with latest `master` as per 9323d52. Let me know if it does or not so I can release a new version with that fix.

If it doesn't, then reopen the bug.

As a side note, if you have some time to discuss your experience with Hasura, I'm interested as I'll start a new project and we have some freedom on what to use, initially thinking of Apollo, but if there are better alternatives I'd be glad to know: barbieri@gmail.com

**Comment by chedburgh** [comment]
Latest master solved this for me, thanks for resolving the problem. 

I am testing Hasura against our TimescaleDb cluster as an extraction mechanism (prototype currently), and want to provide a simple python API access to the data for our users. We will get in touch if we move the project forward (which I hope we do).

**Comment by barbieri** [comment]
nice! I want to know how it plays in real-world environments... do you have other, non PostgreSQL resolvers? Like some REST or some federated GQL doing some other business logic?

**Comment by chedburgh** [comment]
No, this is bit of a first for us. Current access to be database is via some simple java extraction libraries.

If I do manage to move the testing on we may have other APIs and databases I try integrate with it. It's very early stages currently. I suspect performance will be our main concern, since we extract large quantities of data from the database for plotting.

**Comment by barbieri** [comment]
i see, btw if you need to plot stuff it's better to keep number of samples low -- independently of the transport. It all depends on the domain, but much like Stocks, you do have multiple "resolution" of your data, you never plot 5-year window feeding all the intra-day details, you keep intra-day, single day, week, month, ... so you pick the proper one for the "distance" you're viewing. In some cases you may just calculate a single value (ie: avg), in others you may keep auxiliary info (min, max, avg, std-dv) and plot it as well (like candlesticks).

**Comment by chedburgh** [comment]
While our existing software does not do this, I am hoping to move towards this with Views in the database and plotting in a browser. This addresses only some of our data, we are also archiving complex array data that will accessed in bulk, so extraction speed across Hasuea etc remains critical if this is to be a viable pipeline. It's going to be interesting testing it!
