### ISSUE TITLE
linting fails because the `flake8-regex` plugin is still on `pep8`

### ISSUE THREAD

**Issue by jean** [profusion/sgqlc#90]
https://github.com/aristide-n/flake8-regex/blob/master/flake8_regex.py#L6 is still on `pep8` which hits this issue: https://github.com/PyCQA/pycodestyle/issues/728

Changing that to `pycodestyle` seems to work. 

https://github.com/aristide-n/flake8-regex/pull/3

**Comment by barbieri** [comment]
ok, but this PR is not merged yet and pep8 is still used in upstream/released version, no?

**Comment by barbieri** [comment]
see further discussion at #92

**Comment by barbieri** [comment]
this was fixed
