### ISSUE TITLE
Query result works but not natively

### ISSUE THREAD

**Issue by janvdvegt** [profusion/sgqlc#95]
Hi, thank you for this great package. I'm running into an issue that I don't fully understand. I use the code generation and that works well, however when I want to combine the query and the result so that I can use native Python as opposed to the nested dictionary approach it seems to fail.

```
query = Operation(storage_manager.Query)
query.commit_paths(commit_hash=commit_hash,
                       repository_id=repository_id,
                       project_id=project_id)
result = storage_manager_endpoint(query)
```

Result contains:

```
{'data':
  {'commitPaths': 
    {'bucket': 'a-2z2tb', 
    'codePath': 'commits/iris-0x2bb-...de.tar.gz', 
    'virtualEnvironmentPath': 'commits/iris-0x2bb-...nv.tar.gz'}
  }
}
```

So navigating the result as this works:

`result["data"]["commitPaths"]["bucket"]`

When I then combine the query with the result to get a CommitPaths object as follows:

`commit_paths = (query + result).commit_paths`

This object is of the type `CommitPaths()` and contains the `_ContainerTypeMeta__fields` but nothing else and accessing the result by using either `.bucket` or by `['bucket']` leads to `KeyError: 'CommitPaths() has no field bucket'` error. What am I doing wrong?

**Comment by barbieri** [comment]
could you share the actual schema, or a test server? From the name using plural form it may be that the `commitPaths` is actually a list, but in your pasted data it looks like the result is an actual object.

I wonder if it's a schema mismatch or what.

**Comment by janvdvegt** [comment]
Of course:

```
########################################################################
# Output Objects and Interfaces
########################################################################
class CommitPaths(sgqlc.types.Type):
    __schema__ = storage_manager
    __field_names__ = ('bucket', 'code_path', 'virtual_environment_path')
    bucket = sgqlc.types.Field(sgqlc.types.non_null(String), graphql_name='bucket')
    code_path = sgqlc.types.Field(sgqlc.types.non_null(String), graphql_name='codePath')
    virtual_environment_path = sgqlc.types.Field(sgqlc.types.non_null(String), graphql_name='virtualEnvironmentPath')
```

This is what is generated by the code generator, which also fits with my belief. I think the "raw" SQL query result also fits with that. It looks like there is no data whatsoever in the result. This is the Query definition:

```
class Query(sgqlc.types.Type):
    __schema__ = storage_manager
    __field_names__ = ('commit_paths', 'data_snapshot_paths', 'model_paths')
    commit_paths = sgqlc.types.Field(sgqlc.types.non_null(CommitPaths), graphql_name='commitPaths', args=sgqlc.types.ArgDict((
        ('commit_hash', sgqlc.types.Arg(sgqlc.types.non_null(String), graphql_name='commitHash', default=None)),
        ('repository_id', sgqlc.types.Arg(sgqlc.types.non_null(String), graphql_name='repositoryId', default=None)),
        ('project_id', sgqlc.types.Arg(sgqlc.types.non_null(String), graphql_name='projectId', default=None)),
))
    )
```

**Comment by janvdvegt** [comment]
The plural form refers to the fact that there are one or multiple paths returned inside the single object (in this case the code path and the virtual environment path).

**Comment by barbieri** [comment]
damn it, it was so simple i just didn't noticed it until I tested :-D

You must select the fields you want or use `__fields__()` to select all:

```py
query = Operation(storage_manager.Query)
query.commit_paths(commit_hash=commit_hash,
                       repository_id=repository_id,
                       project_id=project_id).__fields__()
```

HOWEVER I noticed an inconsistency I'll fix, if you don't do this, the query is correct: it acts the same, all fields are selected. However the interpretation of the results does not.

**Comment by barbieri** [comment]
check cec911b and let me know if the original code works. In my test it does.

It's not the ideal usage, in GraphQL you're supposed to specify only the fields you use, but since your usage is something I'd expect in simple scripts and the query was already working, matching its behavior when dealing with the results data is nice.
